-- MySQL Script generated by MySQL Workbench
-- Tue Dec  1 14:24:23 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bple_gaming
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bple_gaming
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bple_gaming` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ;
USE `bple_gaming` ;

-- -----------------------------------------------------
-- Table `bple_gaming`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bple_gaming`.`categories` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 44
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `bple_gaming`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bple_gaming`.`products` (
  `createdAt` TIMESTAMP NULL DEFAULT NULL,
  `updatedAt` TIMESTAMP NULL DEFAULT NULL,
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `price` DECIMAL(10,2) NOT NULL,
  `description` VARCHAR(500) NOT NULL,
  `images` VARCHAR(100) NOT NULL,
  `warranty` INT NOT NULL,
  `discount` INT NULL DEFAULT NULL,
  `status` VARCHAR(45) NULL DEFAULT NULL,
  `id_category` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `idCategory_idx` (`id_category` ASC) VISIBLE,
  CONSTRAINT `idCategory`
    FOREIGN KEY (`id_category`)
    REFERENCES `bple_gaming`.`categories` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 46
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `bple_gaming`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bple_gaming`.`users` (
  `createdAt` TIMESTAMP NULL DEFAULT NULL,
  `updatedAt` TIMESTAMP NULL DEFAULT NULL,
  `id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `category` VARCHAR(45) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  `street` VARCHAR(45) NULL DEFAULT NULL,
  `city` VARCHAR(45) NULL DEFAULT NULL,
  `state` VARCHAR(45) NULL DEFAULT NULL,
  `phone` INT NULL DEFAULT NULL,
  `cp` VARCHAR(45) NULL DEFAULT NULL,
  `house_number` VARCHAR(45) NULL DEFAULT NULL,
  `apartment` VARCHAR(45) NULL DEFAULT NULL,
  `floor` VARCHAR(45) NULL DEFAULT NULL,
  `image` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `bple_gaming`.`carts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bple_gaming`.`carts` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_user` INT NOT NULL,
  `id_product` INT NOT NULL,
  `amount` INT NOT NULL,
  `bill` INT NOT NULL,
  `date` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `idUser_idx` (`id_user` ASC) VISIBLE,
  INDEX `idProduct_idx` (`id_product` ASC) VISIBLE,
  CONSTRAINT `idProduct`
    FOREIGN KEY (`id_product`)
    REFERENCES `bple_gaming`.`products` (`id`),
  CONSTRAINT `idUser`
    FOREIGN KEY (`id_user`)
    REFERENCES `bple_gaming`.`users` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
